spring:
  security:
    oauth2:
      client:
        # 1. 서비스 제공자에 대한 정보
        # redirect 할 로그인 페이지가 어딘지
        # access token 을 발급받는 URL 이 어디인지
        # access token 을 제공하여 사용자 정보를 회수할 URL 은 어딘지
        provider:
          # 서비스 제공자 식별자
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

        # 2. 서비스 제공자를 사용하기 위한 정보
        # 클라이언트(즉 우리 서버)를 식별하기 위한 정보
  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
    username: sa
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true

  jwt:
    secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesasdfqve
